#!/bin/sh

cipher="$HOME/.ssh/secrets/age.key"
secrets="$XDG_RUNTIME_DIR/.bubba"
secret="$secrets/age.key"

if [ ! -d "$secrets" ]; then
	mkdir -p "$secrets"
	chmod 0700 "$secrets"
fi

if [ ! -s "$secret" ]; then
	>"$secret"
	chmod 0600 "$secret"
  rage -d "$cipher" > "$secret"
fi

if [ -t 0 ]; then 
  if [ $# -ne 0 ]; then 
    ENCRYPTEDFILE="$1"
  fi
else
  ENCRYPTEDFILE="$(mktemp)"
  while IFS='' read -r line; do
    printf "%s\n" "$line"
  done > "$ENCRYPTEDFILE"
  CLEANUP="$ENCRYPTEDFILE"
fi

if [ -f "$ENCRYPTEDFILE" ]; then
  cat "$ENCRYPTEDFILE" | rage -d -i "$secret"
fi

rm "$CLEANUP"
