#!/bin/sh

hours=2

secrets="$XDG_RUNTIME_DIR/.bubba"

if [ -d "$secrets" ]; then
  created=$(stat -c%W "$secrets")
  fresh=$(date --date="$hours hours ago" '+%s')

  if [ $created -lt $fresh ]; then
    rm -rf "$secrets"
  fi
fi

