copilot_default: &copilot_default copilot/gpt-4.1

common_copilot: &common_copilot
  api_base: https://api.githubcopilot.com
  api_key: "os.environ/COPILOT_API_KEY" 
  rpm: 15
  input_cost_per_token: 0.0
  output_cost_per_token: 0.0
  extra_headers:
    Copilot-Integration-Id: vscode-chat
    Editor-Version: neovim/0.11.1

claude_common: &claude_common
  max_output_tokens: 8192
  max_input_tokens: 90000
  mode: chat
  supports_vision: true
  supports_function_calling: true
  supports_parallel_function_calling: true
  supports_system_messages: true

copilot_claude4: &copilot_claude4
  model: openai/claude-sonnet-4
  max_tokens: 200000
  <<: [*claude_common, *common_copilot]

copilot_base: &copilot_base
  model: openai/gpt-4.1
  max_tokens: 128000
  max_output_tokens: 4096
  max_input_tokens: 64000
  <<: *common_copilot

copilot_claude37: &copilot_claude37
  model: openai/claude-3.7-sonnet
  max_tokens: 200000
  <<: [*claude_common, *common_copilot]

copilot_geminipro: &copilot_geminipro
  model: openai/gemini-2.5-pro
  max_tokens: 90000
  max_output_tokens: 8192
  <<: *common_copilot

model_list:
  - model_name: ollama/*
    litellm_params:
      model: ollama_chat/*
      api_base: http://localhost:11434
  - model_name: boron/*
    litellm_params:
      model: ollama_chat/*
      api_base: http://10.0.0.10:11434
  - model_name: nitrogen/*
    litellm_params:
      model: ollama_chat/*
      api_base: http://10.0.0.11:11434
  - model_name: openai/*
    litellm_params:
      model: openai/*
  - model_name: groq/*
    litellm_params:
      model: groq/*
  - model_name: cloudflare/*
    litellm_params:
      model: cloudflare/*
  - model_name: cerebras/*
    litellm_params:
      model: cerebras/*
  - model_name: sambanova/*
    litellm_params:
      model: sambanova/*
  - model_name: mistral/*
    litellm_params:
      model: mistral/*
  - model_name: codestral/*
    litellm_params:
      model: codestral/*
  - model_name: openrouter/*
    litellm_params:
      model: openrouter/*
  - model_name: anthropic/*
    litellm_params:
      model: anthropic/*
  - model_name: gemini/*
    litellm_params:
      model: gemini/*
  - model_name: github/*
    litellm_params:
      model: github/*
  - model_name: copilot/*
    litellm_params:
      model: openai/*
      <<: *common_copilot
  - model_name: gemma3:12b
    litellm_params:
      model: cloudflare/@cf/google/gemma-3-12b-it
  - model_name: llama33
    litellm_params:
      model: cloudflare/@cf/meta/llama-3.3-70b-instruct-fp8-fast
  - model_name: copilot/claude-4-sonnet
    litellm_params:
      <<: *copilot_claude4
  - model_name: copilot/claude-3.7-sonnet
    litellm_params:
      <<: *copilot_claude37
  - model_name: copilot/claude-3.5-sonnet
    litellm_params:
      model: openai/claude-3.5-sonnet
      max_tokens: 90000
      <<: [*claude_common, *common_copilot]
  - model_name: gemini-pro
    litellm_params:
      <<: *copilot_geminipro
  - model_name: copilot/gemini-2.5-pro
    litellm_params:
      <<: *copilot_geminipro
  - model_name: copilot/gpt-4.1
    litellm_params:
      model: openai/gpt-4.1
      max_tokens: 128000
      max_output_tokens: 4096
      max_input_tokens: 64000
      <<: *common_copilot
  - model_name: boron-phi
    litellm_params:
      model: ollama_chat/hf.co/bartowski/microsoft_Phi-4-mini-instruct-GGUF:IQ4_XS
      api_base: http://10.0.0.10:11434
  - model_name: boron-gemma
    litellm_params:
      model: ollama_chat/hf.co/mradermacher/gemma-3-4b-it-i1-GGUF:Q4_K_S
      api_base: http://10.0.0.10:11434
  - model_name: boron-qwen
    litellm_params:
      model: ollama_chat/hf.co/bartowski/Qwen_Qwen3-4B-GGUF:IQ4_XS
      api_base: http://10.0.0.10:11434
      temperature: 0.7
      top_p: 0.8
      top_k: 20
      min_p: 0
      extra_body:
        enable_thinking: false
  - model_name: boron-embedding
    litellm_params:
      model: ollama/granite-embedding:30m
      api_base: http://10.0.0.10:11434
  - model_name: local-embedding
    litellm_params:
      model: ollama/granite-embedding:30m
      api_base: http://localhost:11434
  - model_name: homecode
    litellm_params:
      model: openrouter/deepseek/deepseek-chat-v3-0324:free
  - model_name: gemma3n
    litellm_params:
      model: openrouter/google/gemma-3n-e4b-it:free
  - model_name: qwen3
    litellm_params:
      model: openrouter/qwen/qwen3-32b:free
      #model: openrouter/qwen/qwen3-235b-a22b:free
      temperature: 0.7
      top_p: 0.8
      top_k: 20
      min_p: 0
      enable_thinking: false
      extra_body:
        reasoning:
          exclude: true
  - model_name: qwen3big
    litellm_params:
      model: openrouter/qwen/qwen3-235b-a22b:free
      enable_thinking: false
      temperature: 0.6
      top_p: 0.95
      top_k: 20
      min_p: 0
      extra_body:
        reasoning:
          exclude: true
          effort: low
  - model_name: workcode
    litellm_params:
      <<: *copilot_claude4
  - model_name: homesimple
    litellm_params:
      <<: *copilot_base
  - model_name: worksimple
    litellm_params:
      <<: *copilot_base
router_settings:
  routing_strategy: simple-shuffle
  fallbacks: [
    {
      "homecode": [
        "qwen3",
        *copilot_default,
        "groq/meta-llama/llama-4-maverick-17b-128e-instruct",
        "ollama/qwen3:8b" 
      ]
    },
    {
      "workcode": [
        "openrouter/anthropic/claude-sonnet-4-20250514",
        "anthropic/claude-sonnet-4-20250514",
        "openrouter/google/gemini-2.5-pro-preview",
        *copilot_default,
        "ollama/devstral" 
      ]
    },
    {
      "homesimple": [
        "groq/meta-llama/llama-4-scout-17b-16e-instruct",
        "openrouter/google/gemma-3-27b-it:free",
        "ollama/gemma3:8b"
      ]
    },
    {
      "worksimple": [
        "groq/meta-llama/llama-4-scout-17b-16e-instruct",
        "openrouter/google/gemma-3-27b-it",
        "ollama/gemma3:8b"
      ]
    },
    {
      "gemini-pro": [
        "openrouter/google/gemini-2.5-pro-preview"
      ]
    },
    {
      "qwen3": [
        "openrouter/qwen/qwen3-235b-a22b"
      ]
    },
    {
      "boron-rerank": [
        "local-rerank"
      ]
    },
    {
      "boron-embedding": [
        "local-embedding"
      ]
    }
  ]
  num_retries: 3

