model_list:
  - model_name: ollama/gemma3:4b
    litellm_params:
      model: ollama/gemma3:4b
      api_base: http://localhost:11434
  - model_name: copilot/claude-3-7-sonnet
    litellm_params:
      model: copilot/claude-3-7-sonnet
      api_base: https://api.githubcopilot.com
      api_key: "os.environ/COPILOT_API_KEY" 
      rpm: 15
      extra_headers: 
        Copilot-Integration-Id: vscode-chat
        Editor-Version: jbowmancargas/0.2.0
router_settings:
  routing_strategy: simple-shuffle

