#!/usr/bin/env python3
import sys

NUM = "0123456789"
SUPERNUM = "⁰¹²³⁴⁵⁶⁷⁸⁹"

TRANS = str.maketrans(NUM, SUPERNUM)


def run():
    sys.stdout.write(sys.stdin.read().translate(TRANS))


if __name__ == "__main__":
    run()
