#!/bin/sh

hours=2

runtime_dir="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
secrets="$runtime_dir/.bubba"

if [ -d "$secrets" ]; then
  created=$(stat -c%W "$secrets")
  fresh=$(date --date="$hours hours ago" '+%s')

  if [ "$created" -lt "$fresh" ]; then
    rm -rf "$secrets"
  fi
fi

