#!/bin/sh

ACTION="$1"
KEY="$2"
AGE_KEY="$HOME/.ssh/secrets/age.key.pub"

SECRETS_DIR="$HOME/.local/share/secrets"
SECRET_VARS="$SECRETS_DIR/secrets.enc.toml"

if [ ! -d "$SECRETS_DIR" ]; then
  mkdir -p "$SECRETS_DIR"
fi

if [ "$ACTION" = "add" ]; then
  TMPFILE="$(mktemp)"
  agegent "$SECRET_VARS" | savar "$KEY" - | rage -a -R "$AGE_KEY" > $TMPFILE
  mv "$TMPFILE" "$SECRET_VARS"
fi

if [ "$ACTION" = "get" ]; then
  agegent "$SECRET_VARS" | savar "$KEY"
fi
