#!/bin/sh

SOCKFILE="$HOME/.ssh-agent.sock"

# start ssh-agent only if it is not running
pidof ssh-agent > /dev/null 2>&1 || rm -f "$SOCKFILE" && ssh-agent -a "$SOCKFILE" -t 4h >"$HOME/.ssh-agent-info"
if [ -f "${HOME}/.ssh-agent-info" ]; then
  . "${HOME}/.ssh-agent-info" >/dev/null
  export SSH_AUTH_SOCK
  export SSH_AGENT_PID
fi
ssh-add -t 8h -l > /dev/null || agegent ~/.ssh/secrets/id_ed25519.age | ssh-add - > /dev/null 2>&1
