#!/bin/sh

target="${1:-C:\Users\jbowman\devel\CargasEnergy}"
targetbase="$(wslpath "$target")"
tgit="$HOME/win/scoop/shims/git.exe -C $target"
echo "Mirroring to $targetbase"

this_branch=$(git branch --show-current)
target_branch=$($tgit branch --show-current)

if [ "$this_branch" != "$target_branch" ]; then
    printf "Refusing to mirror different branches\n"
    exit 1
fi

this_head=$(git rev-parse --short HEAD)
target_head=$($tgit rev-parse --short HEAD)

{
    git ls-files -om --exclude-standard
    git log --name-only --pretty='' --diff-filter=MACRT "$target_head..$this_head"
} | sort -u | while read -r file; do
    if [ -r "$file" ]; then
        targetdir=$(dirname "$file")
        [ -n "$targetdir" ] && mkdir -p "$targetbase/$targetdir"
        cp "$file" "$targetbase/$targetdir/"
    fi
done

