#!/bin/sh
if [ -z "$@" ]; then
    sqlfluff fix --config "$HOME/devel/sql/.sqlfluff" --dialect tsql -f - 2>/dev/null
else
    sqlfluff fix --config "$HOME/devel/sql/.sqlfluff" --dialect tsql -f "$@"
fi
