#!/usr/bin/env python3
import os
import shlex
from functools import cache
from pathlib import Path

from git.repo import Repo


def ticket_changes(repo, file_list: list, prefix: str = ""):
    pending = {}
    for f in file_list:
        p = Path(f)
        parts = p.stem.split("-")
        ticket = parts[0]
        message = " ".join(parts[1:])
        if ticket.isnumeric():
            file = (Path(repo.git_dir).parent / p).resolve()
            folder = file.parent
            title = get_title(folder)
            pending[ticket] = {
                "message": f"{title} {prefix}{message} gz#{ticket}",
                "file": file,
                "folder": folder,
            }

    return pending


def untracked(repo):
    files = repo.untracked_files
    return ticket_changes(repo, files)


def changed(repo):
    files = [d.a_path for d in repo.index.diff(None) if d.change_type == "M"]
    return ticket_changes(repo, files, "update to ")


@cache
def get_title(path: Path):
    title = os.getenv("TITLE", "")
    for folder in [path] + list(path.parents):
        conf = folder / ".envrc"
        if conf.exists():
            contents = conf.read_text()
            lexer = shlex.shlex(contents, posix=True)
            lexer.whitespace_split = True
            title = next(i.split("=")[1] for i in lexer if "TITLE=" in i)
            break
    return title


@cache
def get_repo():
    folder = Path.home() / "devel/DataConversion"
    path = Path.cwd()
    for folder in [path] + list(path.parents):
        gitdir = folder / ".git"
        if gitdir.exists():
            break
    return Repo(folder)


def run():
    repo = get_repo()
    index = repo.index
    for _ticket, info in untracked(repo).items():
        index.add(info["file"])
        index.commit(info["message"])
        print(info["message"])
    for _ticket, info in changed(repo).items():
        index.add(info["file"])
        index.commit(info["message"])
        print(info["message"])


if __name__ == "__main__":
    run()
